


#fofa
fofa_key='你的fofa的api，把我这句替换掉'
fofa_url='https://fofa.info'
fofa_email=''

#是否保存在同一个文件中，如果为True 则直接保存在下面这个文件中，若填写False，则会自动根据搜索的东西创建不同的文件保存
is_save_the_file:True
file_name='result.xlsx'
#这里是需要额外保存的状态码
[0,200, 302, 404, 500]
#size,fofa查询数量
size=100